kind: Deployment
apiVersion: apps/v1
metadata:
  name: client
spec:
  
  # nb de copies
  replicas: 3

  # 3. Which pods are managed by this deployment?
  selector:
    # This must match the labels we set on the pod!
    matchLabels:
      deploy: client
  
  # This template field is a regular pod configuration 
  # nested inside the deployment spec
  template:
    metadata:
      # Set labels on the pod.
      # This is used in the deployment selector.
      labels:
        deploy: client
    spec:
      containers:
        - name: client
          image: joflucki/planets-api:client
          command: ["python", "client.py"]
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"