kind: Deployment
apiVersion: apps/v1
metadata:
  name: server
spec:
  
  # nb de copies
  replicas: 1

  # 3. Which pods are managed by this deployment?
  selector:
    # This must match the labels we set on the pod!
    matchLabels:
      deploy: server
  
  # This template field is a regular pod configuration 
  # nested inside the deployment spec
  template:
    metadata:
      # Set labels on the pod.
      # This is used in the deployment selector.
      labels:
        deploy: server
    spec:
      containers:
        - name: server
          image: joflucki/planets-api:server
          command: ["node", "app.js"]
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"