# apiVersion: v1
# kind: Service
# metadata:
#   name: back-end
# spec:
#   selector:
#     deploy: database
#   ports:
#   - port: 8080
#     protocol: TCP
#     targetPort: 27017

# ---

apiVersion: v1
kind: Service
metadata:
  name: front-end
spec:
  selector:
    deploy: server
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000